Kafka stub documentation
znsio/archived-specmatic-documentation pull request #38
Opened 2023-05-25 06:29 UTC by AdityaSharma6991

2023-05-25 11:27 UTC, joelrosario requested changes

2023-05-25 11:27 UTC, joelrosario commented on documentation/stubbing-kafka.md
> +   // We won't start it though, we will just use some utils.
This comment reads as if we don't start it, but is ambiguous about who 'we' is.

Specmatic won't start it. The test will instantiate and start it directly. Can you say that explicitly please.

2023-05-25 12:53 UTC, AdityaSharma6991 commented on documentation/stubbing-kafka.md
> +   // We won't start it though, we will just use some utils.
removed the comment

2023-05-26 05:42 UTC, joelrosario approved these changes

2023-05-26 05:42 UTC, merged